import type { RoutingVocabularyEntry, RoutingVocabularyFile, RoutingVocabularyLocale, RoutingSignalKind } from "./types.ts";

const entry = (
  kind: RoutingSignalKind,
  id: string,
  locale: RoutingVocabularyLocale,
  phrases: string[],
  negativePhrases?: string[],
): RoutingVocabularyEntry => ({ kind, id, locale, phrases, ...(negativePhrases ? { negativePhrases } : {}) });

export const coreRoutingVocabulary = {
  schemaVersion: "routing-vocabulary/1.0",
  owner: { kind: "core", id: "core" },
  creatableArtifactIds: ["application", "component", "form", "page", "service"],
  entries: [
    entry("action", "create", "en", ["create", "build", "make", "develop", "add"], ["do not create", "don't create", "do not build", "don't build"]),
    entry("action", "create", "ru", ["создай", "создать", "сделай", "собери", "разработай", "добавь", "добавить"], ["не создавай", "не делай"]),
    entry("action", "implement", "en", ["implement", "implementation"]),
    entry("action", "implement", "ru", ["реализуй", "реализовать", "внедри", "внедрить"]),
    entry("action", "modify", "en", ["modify", "change", "update"]),
    entry("action", "modify", "ru", ["измени", "изменить", "обнови", "обновить"]),
    entry("action", "fix", "en", ["fix", "repair"]),
    entry("action", "fix", "ru", ["исправь", "исправить", "почини", "починить"]),
    entry("action", "debug", "en", ["debug", "diagnose"]),
    entry("action", "debug", "ru", ["отладь", "отладить", "диагностируй", "диагностировать"]),
    entry("action", "review", "en", ["review", "audit"]),
    entry("action", "review", "ru", ["ревью", "проведи ревью", "проанализируй"]),
    entry("action", "test", "en", ["test", "tests", "testing"]),
    entry("action", "test", "ru", ["тест", "тесты", "тестирование", "протестируй"]),
    entry("action", "verify", "en", ["verify", "validate", "check"]),
    entry("action", "verify", "ru", ["проверь", "проверить", "валидация"]),
    entry("action", "document", "en", ["document", "documentation"]),
    entry("action", "document", "ru", ["документируй", "документация"]),
    entry("action", "deploy", "en", ["deploy", "deployment"]),
    entry("action", "deploy", "ru", ["разверни", "развернуть", "деплой"]),
    entry("action", "migrate", "en", ["migrate", "migration"]),
    entry("action", "migrate", "ru", ["мигрируй", "миграция", "перенеси"]),
    entry("action", "optimize", "en", ["optimize", "optimization"]),
    entry("action", "optimize", "ru", ["оптимизируй", "оптимизация", "ускорь"]),
    entry("action", "research", "en", ["research"]),
    entry("action", "research", "ru", ["исследуй", "исследование", "изучи"]),
    entry("action", "design", "en", ["design the", "redesign"]),
    entry("action", "design", "ru", ["спроектируй", "разработай дизайн", "сделай редизайн"]),
    entry("action", "configure", "en", ["configure", "configuration"]),
    entry("action", "configure", "ru", ["настрой", "настроить", "конфигурация"]),
    entry("action", "investigate", "en", ["investigate", "investigation"]),
    entry("action", "investigate", "ru", ["расследуй", "расследование", "разберись"]),
    entry("artifact", "page", "ru", ["страница", "странице"]),
    entry("artifact", "component", "ru", ["компонент"]),
    entry("artifact", "form", "ru", ["форма", "форму"]),
    entry("quality", "accessibility", "mixed", ["accessibility", "accessible", "keyboard navigation", "visible focus", "semantic html", "contrast", "sufficient contrast", "screen reader", "wcag", "доступность", "доступный", "доступным", "доступностью", "доступную", "клавиатура", "фокус", "контраст"]),
    entry("quality", "performance", "mixed", ["performance", "производительность"]),
    entry("quality", "security", "mixed", ["security", "безопасность"]),
    entry("quality", "correctness", "mixed", ["correctness", "корректность"]),
    entry("quality", "coverage", "mixed", ["coverage", "покрытие"]),
    entry("quality", "usability", "mixed", ["usability", "usable", "удобство использования"]),
    entry("constraint", "no-network", "mixed", ["without network", "no network", "offline only", "без сети", "без интернета"]),
    entry("constraint", "no-installation", "mixed", ["do not install", "without installation", "не устанавливай", "без установки"]),
    entry("constraint", "read-only", "mixed", ["read only", "только чтение"]),
    entry("acceptance", "tests-pass", "mixed", ["tests pass", "tests passing", "тесты проходят", "тесты должны пройти"]),
    entry("acceptance", "static-analysis-pass", "mixed", ["static analysis passes", "линтер проходит"]),
    entry("acceptance", "security-gates-pass", "mixed", ["security gates pass", "проверки безопасности проходят"]),
    entry("acceptance", "accessibility-gates-pass", "mixed", ["accessibility gates pass", "проверки доступности проходят"]),
    entry("acceptance", "performance-measured", "mixed", ["measure performance", "performance measured", "измерь производительность"]),
    entry("acceptance", "schema-valid", "mixed", ["schema is valid", "схема валидна"]),
    entry("acceptance", "deployment-smoke-pass", "mixed", ["deployment smoke passes", "smoke test passes"]),
  ],
} satisfies RoutingVocabularyFile;
